### ISSUE TITLE
Question about the implementation of sc.EmitPushBigInt

### ISSUE THREAD

**Issue by hactrox** [neo-ngd/neo-gogogo#3]
https://github.com/neo-ngd/neo-gogogo/blob/2e8babf1868e3fd3c6e64c5c45e1c4db79fc32f4/sc/scriptBuilder.go#L95

If number is bigger than 16, say, EmitPushBigInt(128), the above code returns 80, but actually it should be 8000, and if the number is 129, the desired result should be 8100, not 81.

![128](https://user-images.githubusercontent.com/8434402/85111723-51062200-b247-11ea-9da8-a3e365c38e5c.png)
![129](https://user-images.githubusercontent.com/8434402/85111729-52cfe580-b247-11ea-9c12-d29854f9051e.png)

**Comment by joeqian10** [comment]
@hactrox Hi, now the issue is fixed. Thanks!
